name: Split Matches JSON

on:
  push:
    paths:
      - "match.json"   # Trigger only when match.json changes

jobs:
  split:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Split match.json and cleanup old files
        run: |
          node <<'EOF'
          const fs = require('fs');
          const path = require('path');

          const file = 'match.json';
          const raw = fs.readFileSync(file, 'utf8');
          const data = JSON.parse(raw);

          const grouped = {};

          // Group matches by sport
          data.forEach(item => {
            const sport = item.id.trim();
            if (!grouped[sport]) grouped[sport] = [];
            grouped[sport].push({
              id: (grouped[sport].length + 1).toString(),
              title: item.title,
              link: item.link
            });
          });

          // Delete old sport JSON files that no longer exist
          const existing = fs.readdirSync('.').filter(f => f.startsWith('24spn-') && f.endsWith('.json'));
          for (const file of existing) {
            const sportName = file.replace(/^24spn-|\.json$/g, '');
            if (!grouped[sportName]) {
              fs.unlinkSync(file);
              console.log(`🗑️ Deleted old file: ${file}`);
            }
          }

          // Create/update JSON files for each sport
          for (const [sport, matches] of Object.entries(grouped)) {
            const filename = `24spn-${sport}.json`;
            fs.writeFileSync(filename, JSON.stringify(matches, null, 2));
            console.log(`✅ Created/Updated ${filename}`);
          }
          EOF

      - name: Commit and push updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add 24spn-*.json
          git commit -m "Auto-update sport JSON files" || echo "No changes to commit"
          git push
