name: Automated JSON File Generation

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

# REQUIRED FIX: Grant the workflow write access to the repository contents
permissions:
  contents: write

jobs:
  generate_files:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository content
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Using the default token
          token: ${{ secrets.GITHUB_TOKEN }} 
      
      # Step 2: Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      # Step 3: Run the Python script to generate the new files
      - name: Run JSON processing script
        run: python process_json.py
        
      # Step 4: Commit and Push the updated files
      - name: Commit and Push generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: '24spn-*.json' 
          commit_message: 'Automated update: Regenerated category JSON files'
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'actions@github.com'
